export const WORKOUT_ADD = "WORKOUT_ADD";
export const WORKOUT_FETCH = "WORKOUT_FETCH";
export const WORKOUT_DELETE = "WORKOUT_DELETE";
export const WORKOUT_EDIT = "WORKOUT_EDIT";

export const AJAX_BEGIN_CALL = 'AJAX_BEGIN_CALL';

export const WORKOUT_API_FETCH_BEGIN = "WORKOUT_API_FETCH_BEGIN";
export const WORKOUT_API_FETCH_SUCCESS = "WORKOUT_API_FETCH_SUCCESS";
export const WORKOUT_API_FETCH_ERROR = "WORKOUT_API_FETCH_ERROR";

export const WORKOUT_API_ADD_BEGIN = "WORKOUT_API_ADD_BEGIN";
export const WORKOUT_API_ADD_SUCCESS = "WORKOUT_API_ADD_SUCCESS";
export const WORKOUT_API_ADD_ERROR = "WORKOUT_API_ADD_ERROR";

export const WORKOUT_API_EDIT_BEGIN = "WORKOUT_API_EDIT_BEGIN";
export const WORKOUT_API_EDIT_SUCCESS = "WORKOUT_API_EDIT_SUCCESS";
export const WORKOUT_API_EDIT_ERROR = "WORKOUT_API_EDIT_ERROR";



export const WORKOUT_API_DELETE_BEGIN = "WORKOUT_API_DELETE_BEGIN";
export const WORKOUT_API_DELETE_SUCCESS = "WORKOUT_API_DELETE_SUCCESS";
export const WORKOUT_API_DELETE_ERROR = "WORKOUT_API_DELETE_ERROR";

export const AUTHENTICATIONS = {
    LOGGED_IN: 'LOGGED_IN',
    LOGGED_IN_FAIL: 'LOGGED_IN_FAIL',
    LOGGED_OUT: 'LOGGED_OUT'
}