export const WORKOUT_ADD = "WORKOUT_ADD";
export const WORKOUT_FETCH = "WORKOUT_FETCH";
export const WORKOUT_DELETE = "WORKOUT_DELETE";
export const WORKOUT_EDIT = "WORKOUT_EDIT";

export const WORKOUT_API_ADD = "WORKOUT_API_ADD";
export const WORKOUT_API_FETCH = "WORKOUT_API_FETCH";
export const WORKOUT_API_DELETE = "WORKOUT_API_DELETE";
export const WORKOUT_API_EDIT = "WORKOUT_API_EDIT";